/* soapBasicHttpBinding_USCOREIWSCenterEntranceProxy.h
   Generated by gSOAP 2.8.63 for servicel.h

gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef soapBasicHttpBinding_USCOREIWSCenterEntranceProxy_H
#define soapBasicHttpBinding_USCOREIWSCenterEntranceProxy_H
#include "soapH.h"

    class SOAP_CMAC BasicHttpBinding_USCOREIWSCenterEntranceProxy : public soap {
      public:
        /// Endpoint URL of service 'BasicHttpBinding_USCOREIWSCenterEntranceProxy' (change as needed)
        const char *soap_endpoint;
        /// Variables globally declared in servicel.h, if any
        /// Construct a proxy with new managing context
        BasicHttpBinding_USCOREIWSCenterEntranceProxy();
        /// Copy constructor
        BasicHttpBinding_USCOREIWSCenterEntranceProxy(const BasicHttpBinding_USCOREIWSCenterEntranceProxy& rhs);
        /// Construct proxy given a managing context
        BasicHttpBinding_USCOREIWSCenterEntranceProxy(const struct soap&);
        /// Constructor taking an endpoint URL
        BasicHttpBinding_USCOREIWSCenterEntranceProxy(const char *endpoint);
        /// Constructor taking input and output mode flags for the new managing context
        BasicHttpBinding_USCOREIWSCenterEntranceProxy(soap_mode iomode);
        /// Constructor taking endpoint URL and input and output mode flags for the new managing context
        BasicHttpBinding_USCOREIWSCenterEntranceProxy(const char *endpoint, soap_mode iomode);
        /// Constructor taking input and output mode flags for the new managing context
        BasicHttpBinding_USCOREIWSCenterEntranceProxy(soap_mode imode, soap_mode omode);
        /// Destructor deletes deserialized data and managing context
        virtual ~BasicHttpBinding_USCOREIWSCenterEntranceProxy();
        /// Initializer used by constructors
        virtual void BasicHttpBinding_USCOREIWSCenterEntranceProxy_init(soap_mode imode, soap_mode omode);
        /// Return a copy that has a new managing context with the same engine state
        virtual BasicHttpBinding_USCOREIWSCenterEntranceProxy *copy();
        /// Copy assignment
        BasicHttpBinding_USCOREIWSCenterEntranceProxy& operator=(const BasicHttpBinding_USCOREIWSCenterEntranceProxy&);
        /// Delete all deserialized data (uses soap_destroy() and soap_end())
        virtual void destroy();
        /// Delete all deserialized data and reset to default
        virtual void reset();
        /// Disables and removes SOAP Header from message by setting soap->header = NULL
        virtual void soap_noheader();
        /// Get SOAP Header structure (i.e. soap->header, which is NULL when absent)
        virtual ::SOAP_ENV__Header *soap_header();
        /// Get SOAP Fault structure (i.e. soap->fault, which is NULL when absent)
        virtual ::SOAP_ENV__Fault *soap_fault();
        /// Get SOAP Fault string (NULL when absent)
        virtual const char *soap_fault_string();
        /// Get SOAP Fault detail as string (NULL when absent)
        virtual const char *soap_fault_detail();
        /// Close connection (normally automatic, except for send_X ops)
        virtual int soap_close_socket();
        /// Force close connection (can kill a thread blocked on IO)
        virtual int soap_force_close_socket();
        /// Print fault
        virtual void soap_print_fault(FILE*);
    #ifndef WITH_LEAN
    #ifndef WITH_COMPAT
        /// Print fault to stream
        virtual void soap_stream_fault(std::ostream&);
    #endif
        /// Write fault to buffer
        virtual char *soap_sprint_fault(char *buf, size_t len);
    #endif
        /// Web service operation 'ENTRANCE' (returns SOAP_OK or error code)
        virtual int ENTRANCE(_ns1__ENTRANCE *ns1__ENTRANCE, _ns1__ENTRANCEResponse &ns1__ENTRANCEResponse)
        { return this->ENTRANCE(NULL, NULL, ns1__ENTRANCE, ns1__ENTRANCEResponse); }
        virtual int ENTRANCE(const char *soap_endpoint, const char *soap_action, _ns1__ENTRANCE *ns1__ENTRANCE, _ns1__ENTRANCEResponse &ns1__ENTRANCEResponse);
        /// Web service operation 'ENTRANCE_TEST' (returns SOAP_OK or error code)
        virtual int ENTRANCE_USCORETEST(_ns1__ENTRANCE_USCORETEST *ns1__ENTRANCE_USCORETEST, _ns1__ENTRANCE_USCORETESTResponse &ns1__ENTRANCE_USCORETESTResponse)
        { return this->ENTRANCE_USCORETEST(NULL, NULL, ns1__ENTRANCE_USCORETEST, ns1__ENTRANCE_USCORETESTResponse); }
        virtual int ENTRANCE_USCORETEST(const char *soap_endpoint, const char *soap_action, _ns1__ENTRANCE_USCORETEST *ns1__ENTRANCE_USCORETEST, _ns1__ENTRANCE_USCORETESTResponse &ns1__ENTRANCE_USCORETESTResponse);
    };
#endif
